package com.burpfox.extension;

import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import com.burpfox.menu.BurpFoxContextMenu;
import com.burpfox.ui.BurpFoxTab;

import java.io.InputStream;
import java.util.Properties;

/**
 * Main entry point for BurpFox extension.
 */
public class BurpFoxExtension implements BurpExtension {

    private static final String VERSION = loadVersion();
    
    private MontoyaApi api;
    private BurpFoxTab mainTab;

    @Override
    public void initialize(MontoyaApi api) {
        this.api = api;
        this.api.extension().setName("BurpFox");

        // 1. Create Main Tab
        this.mainTab = new BurpFoxTab();
        api.userInterface().registerSuiteTab("BurpFox", mainTab.getUiComponent());

        // 2. Register Context Menu
        api.userInterface().registerContextMenuItemsProvider(new BurpFoxContextMenu(api, mainTab));

        // 3. Register Unload Handler
        api.extension().registerUnloadingHandler(() -> {
            api.logging().logToOutput("Unloading BurpFox... Stopping all scans.");
            mainTab.stopAllScans();
        });

        api.logging().logToOutput("BurpFox extension v" + VERSION + " loaded.");
        api.logging().logToOutput("Dalfox path: " + com.burpfox.core.DalfoxRunner.getDalfoxPath());
    }
    
    /**
     * Loads version from version.properties (generated by Maven resource filtering).
     */
    private static String loadVersion() {
        try {
            InputStream is = BurpFoxExtension.class.getResourceAsStream("/version.properties");
            if (is != null) {
                Properties props = new Properties();
                props.load(is);
                is.close();
                return props.getProperty("version", "dev");
            }
        } catch (Exception e) {
            System.err.println("[BurpFox] Failed to load version: " + e.getMessage());
        }
        return "0.1-dev";
    }
    
    /**
     * Returns the current extension version.
     */
    public static String getVersion() {
        return VERSION;
    }
}
